### ISSUE TITLE
Error handling: InterMine versions

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/bluegenes#236] opened 2018-03-13 16:08 UTC
1. clearly indicate which minimum InterMine version is required on release notes
2. FAIL early if InterMine version is too low. Clear message to dev why it failed. Can't fail later, or silently. Don't want to just "hide" functionality. 

User expects to have feature ABC working. They don't see feature ABC on the results tables. Is it broken? Or is their InterMine not updated with the new web service?

**Comment by yochannah** [comment] 2018-03-13 16:13
hah, 30 seconds too slow! This is a duplicate of #235 ;)

**Closed as completed by yochannah** 2018-03-13 16:13 UTC
